---
- name: Asignar variables a hosts
  hosts: servers
  gather_facts: no
  vars:
  - hostname: localhost
  - dir_IP: 127.0.0.1 
  - user: root
  tasks:
  - name: Debugging
    debug:
     var: hostname, dir_IP , user
